import { useEffect, useState } from "react";
import API from "../services/api";

const date = (value) => value ? new Date(value).toLocaleDateString("en-IN", { day:"2-digit", month:"short", year:"numeric" }) : "—";
export default function AdminRegistrationManagement() {
  const [settings,setSettings]=useState(null), [fee,setFee]=useState(""), [items,setItems]=useState([]), [page,setPage]=useState(1), [pages,setPages]=useState(1), [total,setTotal]=useState(0), [search,setSearch]=useState(""), [paymentStatus,setPaymentStatus]=useState("All"), [registrationStatus,setRegistrationStatus]=useState("All"), [course,setCourse]=useState("All"), [branch,setBranch]=useState("All"), [domain,setDomain]=useState("All"), [from,setFrom]=useState(""), [to,setTo]=useState(""), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [selected,setSelected]=useState(null), [message,setMessage]=useState("");
  const load=async(nextPage=page)=>{setLoading(true);try{const [settingRes,listRes]=await Promise.all([API.get("/admin/registration-settings"),API.get("/admin/registrations",{params:{page:nextPage,limit:10,search,paymentStatus,registrationStatus,course,branch,primaryDomain:domain,from,to}})]);setSettings(settingRes.data.settings);setFee(String(settingRes.data.settings.registrationFee));setItems(listRes.data.items||[]);setPages(listRes.data.totalPages||1);setTotal(listRes.data.total||0);setPage(nextPage);}catch(e){setMessage(e?.response?.data?.message||"Unable to load registration management.");}finally{setLoading(false);}};
  useEffect(()=>{load(1);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
  const save=async(update)=>{setSaving(true);setMessage("");try{const {data}=await API.patch("/admin/registration-settings",update);setSettings(data.settings);setFee(String(data.settings.registrationFee));setMessage(data.message);}catch(e){setMessage(e?.response?.data?.message||"Unable to save settings.");}finally{setSaving(false);}};
  const exportCsv=()=>{const headers=["Registration ID","Name","Email","Phone","Course","Branch","College","Domain","Registration Fee","Payment Status","Registration Status","Registered Date"];const rows=items.map((r)=>[r.registrationId,r.fullName,r.email,r.phone,r.course,r.branch,r.collegeName,r.primaryDomain,r.registrationFee,r.paymentStatus,r.registrationStatus,date(r.createdAt)].map((v)=>`"${String(v||"").replace(/"/g,'""')}"`).join(","));const blob=new Blob([[headers.join(","),...rows].join("\n")],{type:"text/csv"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="internovatech_registrations.csv";link.click();URL.revokeObjectURL(link.href);};
  const inspect=async(id)=>{try{const {data}=await API.get(`/admin/registrations/${id}`);setSelected(data.registration);}catch{setMessage("Unable to load registration details.");}};
  return <section className="admin-table-card mb-4" id="internship-registrations-admin"><div className="d-flex justify-content-between align-items-start gap-3 flex-wrap mb-4"><div><h3 className="admin-section-title mb-1">Internship Registrations Management</h3><p className="text-secondary mb-0">Secure registration payment records and application management.</p></div><button className="btn btn-outline-primary admin-action-btn" onClick={exportCsv} disabled={!items.length}>Export Registrations CSV</button></div>
    {message&&<div className="alert alert-info">{message}</div>}<div className="admin-info-box mb-4"><div className="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><h5 className="fw-bold mb-1">Internship Registration Settings</h5><p className="mb-0 text-secondary">Existing registrations retain their original fee. New payments use this server-side fee.</p></div><label className="mb-0">Registration Fee (₹)<input className="form-control mt-1" type="number" min="1" max="100000" value={fee} onChange={(e)=>setFee(e.target.value)} /></label><button className="btn btn-primary admin-action-btn" disabled={saving} onClick={()=>save({registrationFee:fee})}>{saving?"Saving…":"Save Changes"}</button><button className={`btn ${settings?.registrationEnabled?"btn-outline-danger":"btn-outline-success"} admin-action-btn`} disabled={saving} onClick={()=>save({registrationEnabled:!settings?.registrationEnabled})}>{settings?.registrationEnabled?"Disable Registration":"Enable Registration"}</button></div><small className="text-secondary d-block mt-2">Status: {settings?.registrationEnabled?"Enabled":"Disabled"} · Last updated: {date(settings?.updatedAt)}{settings?.updatedBy?.name?` by ${settings.updatedBy.name}`:""}</small></div>
    <div className="row g-2 mb-3"><div className="col-md-4"><input className="form-control" value={search} placeholder="Search ID, student, email, college or domain" onChange={(e)=>setSearch(e.target.value)} /></div><div className="col-md-2"><select className="form-select" value={paymentStatus} onChange={(e)=>setPaymentStatus(e.target.value)}><option>All</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="created">Created</option><option value="failed">Failed</option></select></div><div className="col-md-2"><select className="form-select" value={registrationStatus} onChange={(e)=>setRegistrationStatus(e.target.value)}><option>All</option><option value="confirmed">Confirmed</option><option value="payment_pending">Payment Pending</option><option value="cancelled">Cancelled</option></select></div><div className="col-md-2"><input className="form-control" placeholder="Course" value={course==="All"?"":course} onChange={(e)=>setCourse(e.target.value||"All")} /></div><div className="col-md-2"><input className="form-control" placeholder="Branch" value={branch==="All"?"":branch} onChange={(e)=>setBranch(e.target.value||"All")} /></div><div className="col-md-4"><input className="form-control" placeholder="Internship domain" value={domain==="All"?"":domain} onChange={(e)=>setDomain(e.target.value||"All")} /></div><div className="col-md-3"><input className="form-control" type="date" value={from} onChange={(e)=>setFrom(e.target.value)} /></div><div className="col-md-3"><input className="form-control" type="date" value={to} onChange={(e)=>setTo(e.target.value)} /></div><div className="col-md-2"><button className="btn btn-outline-primary w-100" onClick={()=>load(1)}>Apply filters</button></div></div>
    <div className="table-responsive"><table className="table align-middle"><thead><tr><th>ID</th><th>Student</th><th>Academic</th><th>Domain</th><th>Fee</th><th>Payment</th><th>Status</th><th>Date</th><th /></tr></thead><tbody>{loading?<tr><td colSpan="9">Loading registrations…</td></tr>:items.length?items.map((r)=><tr key={r._id}><td>{r.registrationId}</td><td><b>{r.fullName}</b><br/><small>{r.email}<br/>{r.phone}</small></td><td>{r.course}<br/><small>{r.branch}<br/>{r.collegeName}</small></td><td>{r.primaryDomain}</td><td>₹{r.registrationFee}</td><td><span className={`badge text-bg-${r.paymentStatus==="paid"?"success":r.paymentStatus==="failed"?"danger":"warning"}`}>{r.paymentStatus}</span></td><td>{r.registrationStatus.replace(/_/g," ")}</td><td>{date(r.createdAt)}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>inspect(r._id)}>View</button></td></tr>):<tr><td colSpan="9">No registrations match these filters.</td></tr>}</tbody></table></div><div className="d-flex justify-content-between align-items-center"><small>{total} registrations · Page {page} / {pages}</small><div className="d-flex gap-2"><button className="btn btn-sm btn-outline-secondary" disabled={page<=1} onClick={()=>load(page-1)}>Prev</button><button className="btn btn-sm btn-outline-secondary" disabled={page>=pages} onClick={()=>load(page+1)}>Next</button></div></div>
    {selected&&<div className="admin-modal-backdrop" onClick={()=>setSelected(null)}><div className="admin-modal-card" onClick={(e)=>e.stopPropagation()}><div className="d-flex justify-content-between mb-3"><div><h3 className="fw-bold mb-1">{selected.registrationId}</h3><p className="mb-0">{selected.fullName} · {selected.primaryDomain}</p></div><button className="btn btn-outline-dark" onClick={()=>setSelected(null)}>Close</button></div><div className="row g-3"><Info title="Personal Information" values={[["Email",selected.email],["Phone",selected.phone],["Location",`${selected.city}, ${selected.state}, ${selected.country}`]]}/><Info title="Academic Information" values={[["Education",selected.educationLevel],["Course",`${selected.course} · ${selected.branch}`],["College",selected.collegeName],["Graduation",selected.graduationYear]]}/><Info title="Internship" values={[["Domain",selected.primaryDomain],["Duration",selected.preferredDuration],["Mode",selected.preferredMode],["Career goal",selected.careerGoal]]}/><Info title="Payment" values={[["Fee",`₹${selected.registrationFee}`],["Payment",selected.paymentStatus],["Order ID",selected.razorpayOrderId||"—"],["Payment ID",selected.razorpayPaymentId||"—"],["Verified",date(selected.paymentVerifiedAt)]]}/></div></div></div>}</section>;
}
function Info({title,values}){return <div className="col-md-6"><div className="admin-info-box h-100"><h5 className="fw-bold mb-3">{title}</h5>{values.map(([k,v])=><p className="mb-2" key={k}><strong>{k}:</strong> {v||"—"}</p>)}</div></div>;}
